Tömasös/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Tömasös.Repository;
using Tömasös.Services;

namespace Tömasös.Controllers
{
    public class HomeController : Controller
    {
        private readonly IDishService _dishService;

        public HomeController(IDishService dishService)
        {
            _dishService = dishService;
        }
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Menu()
        {
            var model = _dishService.GetModel();
            return View(model);
        }
    }
}

Tömasös/ViewComponents/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using Tömasös.Models;

namespace Tömasös.ViewComponents
{
    public class CartViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(List<Dish> cart)
        {

            // cart är bara 0 om vi kommer ifrån en annan sida och går till meny sidan.
            if(cart.Count == 0)
            {
                try
                {
                    // har vi inte lagt till ngt i cart än kommer den här throwa exception och vi skapar en ny
                    cart = JsonSerializer.Deserialize<List<Dish>>(HttpContext.Session.GetString("Cart"));

                 }
                catch (Exception)
                {
                    cart = new List<Dish>();
                    
                }
            }
            return View("Cart", cart);
        }
    }
}

Tömasös/ViewComponents/DishViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Tömasös.Models;

namespace Tömasös.ViewComponents
{
    public class DishViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(List<Product> ingredients)
        {
            string output = String.Join(", ", ingredients.Select(x=> x.ProductName));

            return View("DishIngredients", output);
        }
    }
}

Tömasös/Views/Home/Index.cshtml
<main class="container">
    <div class="index-grid">
        <section class="grid-col-span-2">
            <h1 class="index-title">Bästsäljande just nu</h1>
            <div class="horizontal-cards">
                <a asp-controller="Home" asp-action="Menu">
                    <article>
                        <img src="https://picsum.photos/150" />
                        <h3>Kebabpizza</h3>
                    </article>
                </a>
               <a asp-controller="Home" asp-action="Menu">
                    <article>
                        <img src="https://picsum.photos/150" />
                        <h3>Falafelrulle</h3>
                    </article>
                </a>
               <a asp-controller="Home" asp-action="Menu">
                    <article>
                        <img src="https://picsum.photos/150" />
                        <h3>Calzone</h3>
                    </article>
                </a>
            </div>
           

        </section>
        <section>
            <h1>Öppettider</h1>
             <ul class="indexlist">
                <li>Måndag-Fredag: <span class="primary-colored-text">10:00-22:00</span> </li>
                <li>Lördag: <span class="primary-colored-text">11:00-21:30</span> </li>
                <li><span class="accent-colored-text">Söndag</span>: <span class="primary-colored-text">11:00-20:00</span></li>
            </ul>
            <h1>Hitta Hit</h1>
            <ul class="indexlist">
                <li>Stora Vägen 52</li>
                <li>123 45 Postorten</li>
                <li>Staden</li>
            </ul>
        </section>
        <section class="premiuminfo">
            <h1>Är du Premiummedlem?</h1>
            <p>
                Fråga om <span class="accent-colored-text">medlemskap</span> nästa gång du kommer in.
            </p>
            <p>
                Som medlem får du 20% rabatt när du köper <span class="accent-colored-text">tre</span> eller fler maträtter!               
            </p>
            <p>
                Var 10:e maträtt är även <span class="accent-colored-text">GRATIS</span>!!
            </p>
        </section>
    </div>
</main>

Tömasös/Views/Home/Menu.cshtml
@model Tömasös.ViewModels.DishViewModel

<div class="menunav">
        <ul>
            @foreach (var category in Model.Categories)
            {
                <li>
                    <a href="#@category.Description">@category.Description</a>
                </li>
            }
        </ul>
        @await Component.InvokeAsync("Cart", new {Cart = new List<Dish>()})
    </div>
<div class="container">
    
    

    
    @foreach(var category in Model.Categories)
    {
        <section class="mealcategory" id="@category.Description">
            <h1>@category.Description</h1>
             @foreach(var dish in Model.Dishes.Where(x=> x.DishType == category.DishType1))
            {        
            <a asp-controller="Food"
            asp-action="AddToCart" 
            asp-route-dishId=@dish.DishId
            data-ajax="true"
            data-ajax-method="GET"
            data-ajax-mode="replace"
            data-ajax-update=".cart">
                <div class="meal">
                    <img class="mealimg" src="https://picsum.photos/100">
                    <div class="mealinfo">
                        <h3 class="dishname">@dish.DishName</h3>
                        <p class="mealdescription">@dish.Description</p>
                        @await Component.InvokeAsync("Dish", new {ingredients = dish.Products.ToList()})                   
                        <p class="mealprice">@dish.Price SEK</p>
                    </div>

                </div>
            </a>
         }

        </section>
    }
    
       
</div>